services:
  - type: web
    name: Jobzy
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.16.0
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: skillalign-sih26134-secure-production-secret-key-2026
      - key: NEXT_PUBLIC_APP_NAME
        value: Jobzy
      - key: NEXT_PUBLIC_SIH_ID
        value: SIH26134
      - key: NEXT_PUBLIC_STATE
        value: Maharashtra
      - key: NEXT_PUBLIC_ORG
        value: Government of Maharashtra
